extends Node

const WORLD_SIZE_X = 2667
const WORLD_SIZE_Y = 2000
const ARENA_GAP = 300
const SIGNALING_URL = "wss://mobber.onrender.com"
const PLAYER_SPEED = 300.0
const PLAYER_START_RADIUS = 30.0

const MOB_RADIUS = 15.0
const MOB_SPEED = 120.0
const MOB_MAX_HEALTH = 30.0
const MOB_WANDER_INTERVAL = 2.0
const MOB_COUNT = 5
const KILL_REWARD = 10

const PLAYER_DASH_SPEED = 2400.0
const PLAYER_DASH_DURATION = 0.1
const PLAYER_DASH_COOLDOWN = 0.8

const SWORD_DAMAGE = 10.0
const SWORD_LENGTH = 45.0
const SWORD_WIDTH = 8.0
const SWORD_SWING_DURATION = 0.25
const SWORD_ARC_HALF = 70.0

const MOB_PUSH_FORCE = 80.0       # gentle contact push — friction wins quickly once player passes
const MOB_KNOCKBACK = 5000.0
const MOB_FRICTION = 3000.0      # higher = faster stop after knockback
const MOB_MAX_EXTERNAL_SPEED = 250.0

const MOB_FLEE_SPEED = 220.0
const MOB_FLEE_MAX_HEALTH = 1.0
const MOB_FLEE_RADIUS = 9.0
const MOB_FLEE_DETECTION_RADIUS = 180.0
const MOB_FLEE_STOP_RADIUS = 280.0
const MOB_FLEE_BASIC_SPEED = 160.0
const MOB_WALL_AVOID_MARGIN = 300.0
const MOB_WALL_AVOID_STRENGTH = 2.5
const MOB_FLEE_PANIC_RADIUS = 140.0
const MOB_FLEE_PANIC_SPEED = 340.0
const MOB_FLEE_PANIC_PULSE_FREQ = 10.0

const MOB_BOSS_RADIUS = 40.0
const MOB_BOSS_SPEED = 55.0
const MOB_BOSS_MAX_HEALTH = 150.0
const MOB_BOSS_WORTH = 10

const ARCHETYPE_PALADIN = 0
const ARCHETYPE_PIRATE = 1
const ARCHETYPE_MAGE = 2
const ARCHETYPE_CYBORG = 3
const ARCHETYPE_ASSASSIN = 4
const ARCHETYPE_BERSERKER = 5
const ARCHETYPE_WARLOCK = 6
const ARCHETYPE_NAMES := ["Paladin", "Pirate", "Mage", "Cyborg", "Assassin", "Berserker", "Warlock"]

const SKILL_WARCRY_DURATION = 3.0
const SKILL_WARCRY_SPEED_MULT = 1.7
const SKILL_WARCRY_COOLDOWN = 9.0
const SKILL_BLINK_DISTANCE = 220.0
const SKILL_BLINK_COOLDOWN = 5.0

const SHOP_COST_SEND_MOB = 5
const SHOP_COST_SEND_3_MOBS = 12
const SHOP_COST_SEND_FLEEING = 8
const SHOP_COST_SEND_BOSS = 50
const SHOP_COST_UPGRADE_MOBS = 20
const SHOP_MOB_HEALTH_BONUS = 10.0
const SHOP_UPGRADE_MAX_LEVEL = 3

# Escalating cost formula: base + current_level * increment
const SHOP_COST_SPEED_BASE = 15
const SHOP_COST_SPEED_INC = 10       # 15 / 25 / 35
const SHOP_SPEED_MULT_PER_LEVEL = 0.2

const SHOP_COST_DAMAGE_BASE = 15
const SHOP_COST_DAMAGE_INC = 12      # 15 / 27 / 39
const SHOP_DAMAGE_PER_LEVEL = 3.0

const SHOP_COST_SWORD_SIZE_BASE = 15
const SHOP_COST_SWORD_SIZE_INC = 12  # 15 / 27 / 39
const SHOP_SWORD_SIZE_PER_LEVEL = 0.2

const SHOP_COST_ATTACK_SPEED_BASE = 20
const SHOP_COST_ATTACK_SPEED_INC = 15 # 20 / 35 / 50
const SHOP_ATTACK_SPEED_PER_LEVEL = 0.2

# Debuff item IDs (used in _apply_purchase)
const DEBUFF_NO_DASH  = 8
const DEBUFF_FRENZY   = 9
const DEBUFF_SILENCE  = 10
const DEBUFF_INVERT   = 11

const DEBUFF_COST_NO_DASH = 15
const DEBUFF_COST_FRENZY  = 20
const DEBUFF_COST_SILENCE = 25
const DEBUFF_COST_INVERT  = 40

const DEBUFF_DUR_NO_DASH = 8.0
const DEBUFF_DUR_FRENZY  = 10.0
const DEBUFF_DUR_SILENCE = 6.0
const DEBUFF_DUR_INVERT  = 5.0

const DEBUFF_FRENZY_SPEED_MULT = 1.6

const SHOP_COST_SKILL_BASE = 25
const SHOP_COST_SKILL_INC = 20   # 25 / 45 / 65
const SHOP_SKILL_CD_REDUCTION_PER_LEVEL = 0.15